server:
  port: 8081

spring:
  application:
    name: ms-transaction
  datasource:
    url: jdbc:postgresql://pg-db:5432/challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace